# Generated by Django 5.2.6 on 2025-09-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='duty_segments',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='day',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='driving_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='off_duty_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='on_duty_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='sleeper_hours',
            field=models.FloatField(default=0),
        ),
    ]
